name: Publish LUXE software image
description: |
  Loads a LUXE-release stack from spack cache.
  This workflow builds the image and pushes it to the registry.

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/luxe-sw-${{ inputs.os }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./Docker
          file: ./Docker/Dockerfile
          build-args: |
            OS=${{ inputs.os }}
            GITHUB_REPOSITORY=${{ github.repository }}
            LUXE_SHA=${{ github.sha }}
            SPACK_BUILDCACHE=oci://ghcr.io/${{ github.repository_owner }}/luxe-buildcache
            OCI_USERNAME=${{ github.actor }}
          secrets: |
            "ocipass=${{ secrets.GITHUB_TOKEN }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
